import type { Schema as ES } from "effect"
import { Effect } from "effect"
import {
  type GraphQLField,
  type NestedType,
  type WalkError,
  walkCollectionSchema,
} from "./walker.js"

/**
 * Header comment for generated GraphQL file
 */
const GENERATED_HEADER = `# This file is auto-generated by cli/generate-rxdb
# Do not edit manually. Changes will be overwritten.
# Source: @pf/rxdb-collections`

/**
 * Generate the complete GraphQL schema for all RxDB collections
 */
export const generateGraphQL = (
  // biome-ignore lint/suspicious/noExplicitAny: legacy code
  collections: Record<string, ES.Schema<any, any, any>>,
): Effect.Effect<string, WalkError> =>
  Effect.gen(function* () {
    const parts: string[] = []

    // Add generated file header
    parts.push(GENERATED_HEADER)

    // Add scalar definitions
    parts.push(generateScalars())

    // Add RxDB base types
    parts.push(generateRxDbBaseTypes())

    // Add Query, Mutation, Subscription type declarations
    const queryFields: string[] = []
    const mutationFields: string[] = []
    const subscriptionFields: string[] = []

    // Generate types for each collection
    for (const [collectionName, schema] of Object.entries(collections)) {
      const collectionTypes = yield* walkCollectionSchema(
        schema.ast,
        collectionName,
      )

      // Generate nested types first (they need to be defined before being used)
      for (const nestedType of collectionTypes.nestedTypes) {
        parts.push(generateNestedType(nestedType))
        parts.push(
          generateNestedInputType(nestedType, collectionTypes.nestedTypes),
        )
      }

      // Generate main type
      parts.push(generateCollectionType(collectionName, collectionTypes.fields))

      // Generate PullBulk type
      parts.push(generatePullBulkType(collectionName))

      // Generate Push input types
      parts.push(
        ...generatePushInputTypes(
          collectionName,
          collectionTypes.fields,
          collectionTypes.nestedTypes,
        ),
      )

      // Add operations
      queryFields.push(generateQueryField(collectionName))
      mutationFields.push(generateMutationField(collectionName))
      subscriptionFields.push(generateSubscriptionField(collectionName))
    }

    // Add Query type
    parts.push(generateQueryType(queryFields))

    // Add Mutation type
    parts.push(generateMutationType(mutationFields))

    // Add Subscription type
    parts.push(generateSubscriptionType(subscriptionFields))

    return `${parts.join("\n\n")}\n`
  })

/**
 * Generate scalar type definitions
 */
const generateScalars = (): string => {
  return `scalar DateTimeISO
scalar JSON`
}

/**
 * Generate RxDB base interface and checkpoint types
 */
const generateRxDbBaseTypes = (): string => {
  return `interface RxDbDocument {
  id: ID!
  updatedAt: Float!
  deleted: Boolean!
}

input PullCheckpoint {
  id: String!
  updatedAt: Float!
  mode: PullCheckpointMode
  backfillHead: PullCheckpointBoundaryInput
}

input PullCheckpointBoundaryInput {
  id: String!
  updatedAt: Float!
}

enum PullCheckpointMode {
  LIVE_BACKFILL
  INCREMENTAL
}

type BulkCheckpoint {
  id: String!
  updatedAt: Float!
  mode: PullCheckpointMode
  backfillHead: BulkCheckpointBoundary
}

type BulkCheckpointBoundary {
  id: String!
  updatedAt: Float!
}`
}

/**
 * Generate a nested GraphQL type (for nested structs)
 */
const generateNestedType = (nestedType: NestedType): string => {
  const fieldDefinitions = nestedType.fields
    .map((field) => {
      const nullability = field.nullable ? "" : "!"
      return `  ${field.name}: ${field.type}${nullability}`
    })
    .join("\n")

  return `type ${nestedType.name} {
${fieldDefinitions}
}`
}

/**
 * Generate a nested GraphQL input type (for nested structs in mutations)
 */
const generateNestedInputType = (
  nestedType: NestedType,
  allNestedTypes: readonly NestedType[],
): string => {
  const fieldDefinitions = nestedType.fields
    .map((field) => {
      const nullability = field.nullable ? "" : "!"
      const inputType = getInputTypeName(field.type, allNestedTypes)
      return `  ${field.name}: ${inputType}${nullability}`
    })
    .join("\n")

  return `input ${nestedType.name}Input {
${fieldDefinitions}
}`
}

/**
 * The deleted field is required by RxDB replication protocol but cannot be
 * in the Effect Schema (RxDB handles it internally). We inject it here.
 */
const RXDB_DELETED_FIELD = "  deleted: Boolean!"

/**
 * Generate the main GraphQL type for a collection
 */
const generateCollectionType = (
  collectionName: string,
  fields: readonly GraphQLField[],
): string => {
  const fieldDefinitions = fields
    .map((field) => {
      const nullability = field.nullable ? "" : "!"
      return `  ${field.name}: ${field.type}${nullability}`
    })
    .join("\n")

  return `type ${collectionName} implements RxDbDocument {
${fieldDefinitions}
${RXDB_DELETED_FIELD}
}`
}

/**
 * Generate the PullBulk type for a collection
 */
const generatePullBulkType = (collectionName: string): string => {
  return `type ${collectionName}PullBulk {
  documents: [${collectionName}!]!
  checkpoint: BulkCheckpoint
}`
}

/**
 * Get the input type name for a field (handles nested types and arrays)
 */
const getInputTypeName = (
  fieldType: string,
  nestedTypes: readonly NestedType[],
): string => {
  // Handle array types: [TypeName!]! -> [TypeNameInput!]!
  const arrayMatch = fieldType.match(/^\[(.+?)(!?)\](!?)$/)
  if (arrayMatch) {
    const innerType = arrayMatch[1] ?? ""
    const innerBang = arrayMatch[2] ?? ""
    const outerBang = arrayMatch[3] ?? ""
    const inputInnerType = getInputTypeName(innerType, nestedTypes)
    return `[${inputInnerType}${innerBang}]${outerBang}`
  }

  // Check if this field type is a nested type
  const isNestedType = nestedTypes.some((nt) => nt.name === fieldType)
  if (isNestedType) {
    return `${fieldType}Input`
  }
  return fieldType
}

/**
 * Generate Push input types for a collection
 */
const generatePushInputTypes = (
  collectionName: string,
  fields: readonly GraphQLField[],
  nestedTypes: readonly NestedType[],
): string[] => {
  const inputFields = fields
    .map((field) => {
      const nullability = field.nullable ? "" : "!"
      const inputType = getInputTypeName(field.type, nestedTypes)
      return `  ${field.name}: ${inputType}${nullability}`
    })
    .join("\n")

  // Include deleted field in input types (required by RxDB replication protocol)
  const assumedMasterStateInput = `input ${collectionName}InputPushRowT0AssumedMasterStateT0 {
${inputFields}
${RXDB_DELETED_FIELD}
}`

  const newDocumentStateInput = `input ${collectionName}InputPushRowT0NewDocumentStateT0 {
${inputFields}
${RXDB_DELETED_FIELD}
}`

  // assumedMasterState is nullable: null for inserts, required for updates (conflict detection)
  const pushRowInput = `input ${collectionName}InputPushRow {
  assumedMasterState: ${collectionName}InputPushRowT0AssumedMasterStateT0
  newDocumentState: ${collectionName}InputPushRowT0NewDocumentStateT0!
}`

  return [assumedMasterStateInput, newDocumentStateInput, pushRowInput]
}

/**
 * Generate query field for a collection
 */
const generateQueryField = (collectionName: string): string => {
  const extraArgs =
    collectionName === "Execution"
      ? ", includeRunning: Boolean, historySince: Float"
      : ""
  return `  pull${collectionName}(checkpoint: PullCheckpoint, limit: Int!${extraArgs}): ${collectionName}PullBulk!`
}

/**
 * Generate mutation field for a collection
 */
const generateMutationField = (collectionName: string): string => {
  return `  push${collectionName}(writeRows: [${collectionName}InputPushRow!]): [${collectionName}!]!`
}

/**
 * Generate subscription field for a collection
 */
const generateSubscriptionField = (collectionName: string): string => {
  return `  stream${collectionName}: ${collectionName}PullBulk!`
}

/**
 * Generate the Query type
 */
const generateQueryType = (fields: string[]): string => {
  return `type Query {
${fields.join("\n")}
}`
}

/**
 * Generate the Mutation type
 */
const generateMutationType = (fields: string[]): string => {
  return `type Mutation {
  # Returns a list of all conflicts
  # If no document write caused a conflict, return an empty list.
${fields.join("\n")}
}`
}

/**
 * Generate the Subscription type
 */
const generateSubscriptionType = (fields: string[]): string => {
  return `type Subscription {
${fields.join("\n")}
}`
}
