import type { Schema as ES } from "effect"
import { gql } from "graphql-request"
import type { RxJsonSchema, StringKeys } from "rxdb/plugins/core"
import type { DraftProcessExecutionSchema } from "@pf/rxdb-collections"
import draftProcessExecutionRxdbSchema from "@pf/rxdb-collections/generated/draft-process-execution-schema.json"
import type {
  PullCheckpoint,
  PullDraftProcessExecutionQueryVariables,
} from "../generated/gql/graphql"

/**
 * Database and collection configuration for draft process executions.
 * These exports are used by DatabaseProvider to initialize RxDB.
 */

// Derive TypeScript type from Effect Schema (encoded form for JSON storage)
export type DraftProcessExecutionDocType = ES.Schema.Encoded<
  typeof DraftProcessExecutionSchema
>

// Use pre-generated RxDB-compatible JSON Schema (generated by cli/generate-rxdb)
export const draftProcessExecutionSchema: RxJsonSchema<DraftProcessExecutionDocType> =
  {
    title: "Draft process executions",
    version: 13,
    primaryKey: "id",
    type: "object",
    additionalProperties: false,
    properties:
      draftProcessExecutionRxdbSchema.properties as RxJsonSchema<DraftProcessExecutionDocType>["properties"],
    indexes: [],
    required:
      draftProcessExecutionRxdbSchema.required as StringKeys<DraftProcessExecutionDocType>[],
  }

export const migrationStrategies = {
  // Migration from version 0 to 1: add processId field
  1: () => null,
  // Migration from version 1 to 2: add deleted field
  2: () => null,
  // Migration from version 2 to 3: allow decimal timestamps
  3: (oldDoc: unknown) => oldDoc,
  // Migration from version 3 to 4: remove updatedAt constraints
  4: (oldDoc: unknown) => oldDoc,
  // Migration from version 4 to 5: remove updatedAt index
  5: (oldDoc: unknown) => oldDoc,
  // Migration from version 5 to 6
  6: (oldDoc: unknown) => oldDoc,
  // Migration from version 6 to 7
  7: (oldDoc: unknown) => ({
    ...(oldDoc as Record<string, unknown>),
    state: {},
  }),
  // Migration from version 7 to 8
  8: (oldDoc: unknown) => oldDoc,
  // Migration from version 8 to 9
  9: (oldDoc: unknown) => oldDoc,
  // Migration from version 9 to 10
  10: (oldDoc: unknown) => oldDoc,
  // Migration from version 10 to 11
  11: (oldDoc: unknown) => oldDoc,
  // Migration from version 11 to 12
  12: (oldDoc: unknown) => oldDoc,
  // Migration from version 12 to 13: add startStepPath field - delete existing documents
  13: () => null,
}

export const pullQueryBuilder = (
  checkpoint: PullCheckpoint | undefined,
  limit: number,
) => {
  const query = gql /* GraphQL */`
    query PullDraftProcessExecution($checkpoint: PullCheckpoint, $limit: Int!) {
      pullDraftProcessExecution(checkpoint: $checkpoint, limit: $limit) {
        documents {
          id
          processId
          name
          startStepPath
          state
          fieldsCompleted
          totalFields
          updatedAt
          deleted
          lastSaved
        }
        checkpoint {
          id
          updatedAt
        }
      }
    }
  `
  return {
    query,
    operationName: "PullDraftProcessExecution",
    variables: {
      checkpoint,
      limit,
    } satisfies PullDraftProcessExecutionQueryVariables,
  }
}

export const pushQueryBuilder = (rows: unknown) => {
  const query = `
    mutation PushDraftProcessExecution($writeRows: [DraftProcessExecutionInputPushRow!]) {
        pushDraftProcessExecution(writeRows: $writeRows) {
          id
          processId
          name
          startStepPath
          state
          fieldsCompleted
          totalFields
          updatedAt
          deleted
          lastSaved
        }
    }
    `
  const variables = {
    writeRows: rows,
  }
  return {
    query,
    operationName: "PushDraftProcessExecution",
    variables,
  }
}

export const pullStreamQueryBuilder = () => {
  const query = gql /* GraphQL */`
    subscription StreamDraftProcessExecution {
      streamDraftProcessExecution {
        documents {
          id
          processId
          name
          startStepPath
          state
          fieldsCompleted
          totalFields
          updatedAt
          deleted
          lastSaved
        }
        checkpoint {
          id
          updatedAt
        }
      }
    }
  `
  return {
    query,
    operationName: "StreamDraftProcessExecution",
    variables: {},
  }
}

export const deletedField = "deleted"
