import type { Schema as ES } from "effect"
import { gql } from "graphql-request"
import type { RxJsonSchema, StringKeys } from "rxdb/plugins/core"
import type { ExecutionSchema } from "@pf/rxdb-collections"
import executionRxdbSchema from "@pf/rxdb-collections/generated/execution-schema.json"
import type {
  PullCheckpoint,
  PullExecutionQueryVariables,
} from "../generated/gql/graphql"

/**
 * Database and collection configuration for executions.
 * These exports are used by DatabaseProvider to initialize RxDB.
 */

/**
 * Number of weeks of execution history to sync for dashboard metrics.
 * Running executions bypass this window on the first initial-sync request.
 */
const EXECUTION_SYNC_WEEKS = 5

// Derive TypeScript type from Effect Schema (encoded form for JSON storage)
export type ExecutionDocType = ES.Schema.Encoded<typeof ExecutionSchema>

// Use pre-generated RxDB-compatible JSON Schema (generated by cli/generate-rxdb)
export const executionSchema: RxJsonSchema<ExecutionDocType> = {
  title: "Executions",
  version: 14,
  primaryKey: "id",
  type: "object",
  additionalProperties: false,
  properties:
    executionRxdbSchema.properties as RxJsonSchema<ExecutionDocType>["properties"],
  indexes: [],
  required: executionRxdbSchema.required as StringKeys<ExecutionDocType>[],
}

export const migrationStrategies = {
  // New terminal outcome and server-owned refusal reasons.
  14: () => null,
  // Repull server-owned execution scheduling metadata and capabilities.
  13: () => null,
  // v0 -> v1: Made providerUser field nullable in steps array
  1: (oldDoc: ExecutionDocType) => oldDoc,
  // v1 -> v2: Added role, startedAt, completedAt fields to steps
  2: (oldDoc: ExecutionDocType) => oldDoc,
  // v2 -> v3: Added estimatedCompletionAt and slaTargetAt fields
  3: (oldDoc: ExecutionDocType) => oldDoc,
  // v3 -> v4: Added id field to providerUser in steps
  4: (oldDoc: ExecutionDocType) => oldDoc,
  // v4 -> v5: Added slaWarningAt field
  5: (oldDoc: ExecutionDocType) => oldDoc,
  // v5 -> v6: Added Failed status + failureReason
  6: (oldDoc: ExecutionDocType) => oldDoc,
  // v6 -> v7: Added canRestartExecution permission flag
  7: (oldDoc: ExecutionDocType) => ({
    ...oldDoc,
    canRestartExecution: oldDoc.canRestartExecution ?? false,
  }),
  // v7 -> v8: Added embedded-form submitter metadata on steps
  8: (oldDoc: ExecutionDocType) => oldDoc,
  // v8 -> v9: Added direct-assignee email on steps
  9: (oldDoc: ExecutionDocType) => oldDoc,
  // v9 -> v10: Added canAbandonExecution permission flag
  10: (oldDoc: ExecutionDocType) => ({
    ...oldDoc,
    canAbandonExecution: oldDoc.canAbandonExecution ?? false,
  }),
  // v10 -> v11: Added Correction Required step status
  11: (oldDoc: ExecutionDocType) => oldDoc,
  12: (oldDoc: ExecutionDocType) => oldDoc,
}

export const pullQueryBuilder = (
  checkpoint: PullCheckpoint | undefined,
  limit: number,
) => {
  // Initial sync includes all Running executions plus recent terminal history.
  // Subsequent syncs use the stored checkpoint for incremental updates.
  const historySince =
    Date.now() - EXECUTION_SYNC_WEEKS * 7 * 24 * 60 * 60 * 1000
  const effectiveCheckpoint: PullCheckpoint = checkpoint ?? {
    id: "",
    updatedAt: historySince,
  }

  const query = gql /* GraphQL */`
    query PullExecution($checkpoint: PullCheckpoint, $limit: Int!, $includeRunning: Boolean, $historySince: Float) {
      pullExecution(checkpoint: $checkpoint, limit: $limit, includeRunning: $includeRunning, historySince: $historySince) {
        documents {
          id
          updatedAt
          processStateId
          withoutWaiting
          processName
          processPath
          canAbandonExecution
          canRestartExecution
          status
          failureReason
          abandonedReason
          notStartedReason
          startedAt
          finishedAt
          completedSteps
          totalSteps
          durationMs
          estimatedCompletionAt
          slaWarningAt
          slaTargetAt
          deleted
          steps {
            id
            name
            path
            status
            failureReason
            notStartedReason
            role {
              id
              name
            }
            submittedViaEmbeddedForm
            externalSubmitterEmail
            assignedProviderUserEmail
            providerUser {
              id
              firstName
              lastName
              picture
              orgUnit
            }
            startedAt
            completedAt
          }
        }
        checkpoint {
          id
          updatedAt
        }
      }
    }
  `
  return {
    query,
    operationName: "PullExecution",
    variables: {
      checkpoint: effectiveCheckpoint,
      includeRunning: checkpoint === undefined,
      historySince,
      limit,
    } satisfies PullExecutionQueryVariables,
  }
}

export const pullStreamQueryBuilder = () => {
  const query = gql /* GraphQL */`
    subscription StreamExecution {
      streamExecution {
        documents {
          id
          updatedAt
          processStateId
          withoutWaiting
          processName
          processPath
          canAbandonExecution
          canRestartExecution
          status
          failureReason
          abandonedReason
          notStartedReason
          startedAt
          finishedAt
          completedSteps
          totalSteps
          durationMs
          estimatedCompletionAt
          slaWarningAt
          slaTargetAt
          deleted
          steps {
            id
            name
            path
            status
            failureReason
            notStartedReason
            role {
              id
              name
            }
            submittedViaEmbeddedForm
            externalSubmitterEmail
            assignedProviderUserEmail
            providerUser {
              id
              firstName
              lastName
              picture
              orgUnit
            }
            startedAt
            completedAt
          }
        }
        checkpoint {
          id
          updatedAt
        }
      }
    }
  `
  return {
    query,
    operationName: "StreamExecution",
    variables: {},
  }
}

export const deletedField = "deleted"
