import type { Schema as ES } from "effect"
import { gql } from "graphql-request"
import type { RxJsonSchema, StringKeys } from "rxdb/plugins/core"
import type { ProcessSchema } from "@pf/rxdb-collections"
import processRxdbSchema from "@pf/rxdb-collections/generated/process-schema.json"
import type {
  PullCheckpoint,
  PullProcessQueryVariables,
} from "../generated/gql/graphql"

/**
 * Database and collection configuration for processes.
 * These exports are used by DatabaseProvider to initialize RxDB.
 */

// Derive TypeScript type from Effect Schema (encoded form for JSON storage)
export type ProcessDocType = ES.Schema.Encoded<typeof ProcessSchema>

// Use pre-generated RxDB-compatible JSON Schema (generated by cli/generate-rxdb)
export const processSchema: RxJsonSchema<ProcessDocType> = {
  title: "Processes",
  version: 3,
  primaryKey: "id",
  type: "object",
  additionalProperties: false,
  properties:
    processRxdbSchema.properties as RxJsonSchema<ProcessDocType>["properties"],
  indexes: [],
  required: processRxdbSchema.required as StringKeys<ProcessDocType>[],
}

export const migrationStrategies = {
  // Repull server-owned execution scheduling metadata and capabilities.
  3: () => null,
  // Version 1: Added startStepPath field - remove old docs, they'll be pulled fresh
  1: () => null,
  // Version 2: Removed lastStarted field - remove old docs, they'll be pulled fresh
  2: () => null,
}

export const pullQueryBuilder = (
  checkpoint: PullCheckpoint | undefined,
  limit: number,
) => {
  const query = gql /* GraphQL */`
    query PullProcess($checkpoint: PullCheckpoint, $limit: Int!) {
      pullProcess(checkpoint: $checkpoint, limit: $limit) {
        documents {
          id
          updatedAt
          name
          path
          activeInstances
          category
          duration
          formFieldCount
          purpose
          isFavorite
          orgUnit {
            id
            name
            level
          }
          canSkipScheduleWaits
          startStepPath
          deleted
        }
        checkpoint {
          id
          updatedAt
        }
      }
    }
  `
  return {
    query,
    operationName: "PullProcess",
    variables: {
      checkpoint,
      limit,
    } satisfies PullProcessQueryVariables,
  }
}

export const pullStreamQueryBuilder = () => {
  const query = gql /* GraphQL */`
    subscription StreamProcess {
      streamProcess {
        documents {
          id
          updatedAt
          name
          path
          activeInstances
          category
          duration
          formFieldCount
          purpose
          isFavorite
          orgUnit {
            id
            name
            level
          }
          canSkipScheduleWaits
          startStepPath
          deleted
        }
        checkpoint {
          id
          updatedAt
        }
      }
    }
  `
  return {
    query,
    operationName: "StreamProcess",
    variables: {},
  }
}

export const deletedField = "deleted"
