import type { Schema as ES } from "effect"
import { gql } from "graphql-request"
import type { RxJsonSchema, StringKeys } from "rxdb/plugins/core"
import type { TodoSchema } from "@pf/rxdb-collections"
import todoRxdbSchema from "@pf/rxdb-collections/generated/todo-schema.json"
import type {
  PullCheckpoint,
  PullTodoQueryVariables,
} from "../generated/gql/graphql"

/**
 * Database and collection configuration for todos.
 * These exports are used by DatabaseProvider to initialize RxDB.
 */

// Derive TypeScript type from Effect Schema (encoded form for JSON storage)
export type TodoDocType = ES.Schema.Encoded<typeof TodoSchema>

// Use pre-generated RxDB-compatible JSON Schema (generated by cli/generate-rxdb)
export const todoSchema: RxJsonSchema<TodoDocType> = {
  title: "Todos",
  version: 4,
  primaryKey: "id",
  type: "object",
  additionalProperties: false,
  properties:
    todoRxdbSchema.properties as RxJsonSchema<TodoDocType>["properties"],
  indexes: [],
  required: todoRxdbSchema.required as StringKeys<TodoDocType>[],
}

export const migrationStrategies = {
  // v0 -> v1: Added stepPath field. Return null to discard old documents and refetch.
  1: () => null,
  // v1 -> v2: Added summary field. Return null to discard old documents and refetch.
  2: () => null,
  // v2 -> v3: Changed assignedAt/dueAt from Float to DateTimeISO. Return null to discard old documents and refetch.
  3: () => null,
  // v3 -> v4: Added Correction Required todo status. Return null to discard old documents and refetch.
  4: () => null,
}

export const pullQueryBuilder = (
  checkpoint: PullCheckpoint | undefined,
  limit: number,
) => {
  const query = gql /* GraphQL */`
    query PullTodo($checkpoint: PullCheckpoint, $limit: Int!) {
      pullTodo(checkpoint: $checkpoint, limit: $limit) {
        documents {
          id
          updatedAt
          processExecutionId
          flowId
          processName
          stepName
          stepPath
          role
          description
          status
          priority
          assignedAt
          dueAt
          formComplexity
          deleted
          summary {
            label
            value
          }
        }
        checkpoint {
          id
          updatedAt
          mode
          backfillHead {
            id
            updatedAt
          }
        }
      }
    }
  `
  return {
    query,
    operationName: "PullTodo",
    variables: {
      checkpoint,
      limit,
    } satisfies PullTodoQueryVariables,
  }
}

export const pullStreamQueryBuilder = () => {
  const query = gql /* GraphQL */`
    subscription StreamTodo {
      streamTodo {
        documents {
          id
          updatedAt
          processExecutionId
          flowId
          processName
          stepName
          stepPath
          role
          description
          status
          priority
          assignedAt
          dueAt
          formComplexity
          deleted
          summary {
            label
            value
          }
        }
        checkpoint {
          id
          updatedAt
          mode
        }
      }
    }
  `
  return {
    query,
    operationName: "StreamTodo",
    variables: {},
  }
}

export const deletedField = "deleted"
