import { createHash } from "node:crypto"
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { generateOrganisationFrontendPluginComposition } from "../scripts/generate-organisation-plugin-composition"
import { afterEach, describe, expect, test } from "bun:test"

let tempDir: string | undefined

const generate = (
  plugins: unknown,
  officialArtifacts = false,
): { readonly loaders: string; readonly preparation: string } => {
  tempDir = mkdtempSync(join(tmpdir(), "dashboard-distribution-"))
  mkdirSync(join(tempDir, "generated"), { recursive: true })
  const manifestPath = join(tempDir, "frontend-manifest.json")
  writeFileSync(manifestPath, `${JSON.stringify({ version: 3, plugins })}\n`)
  if (officialArtifacts) {
    const postHogBundle =
      'export const plugin={id:"analytics.posthog",activate:()=>{}};export const shouldActivate=()=>true\n'
    const postHogSha256 = createHash("sha256")
      .update(postHogBundle)
      .digest("hex")
    const googleDriveBundle =
      'export const plugin={id:"google-drive",activate:(host)=>host.formRenderers.register({type:"google-drive",renderer:()=>null})};export const shouldActivate=()=>true\n'
    const googleDriveSha256 = createHash("sha256")
      .update(googleDriveBundle)
      .digest("hex")
    const googleDriveStylesheet = `@source "./${googleDriveSha256}.js";\n`
    const googleDriveStylesheetSha256 = createHash("sha256")
      .update(googleDriveStylesheet)
      .digest("hex")
    mkdirSync(join(tempDir, "browser-plugins"), { recursive: true })
    writeFileSync(
      join(tempDir, "browser-plugins", `${postHogSha256}.js`),
      postHogBundle,
    )
    writeFileSync(
      join(tempDir, "browser-plugins", `${googleDriveSha256}.js`),
      googleDriveBundle,
    )
    writeFileSync(
      join(tempDir, "browser-plugins", `${googleDriveStylesheetSha256}.css`),
      googleDriveStylesheet,
    )
    writeFileSync(
      join(tempDir, "browser-plugins.json"),
      `${JSON.stringify({
        format: "processfocus/browser-plugins",
        version: 1,
        plugins: [
          {
            identity: "analytics.posthog",
            category: "analytics",
            hostInterfaceVersion: 1,
            path: `browser-plugins/${postHogSha256}.js`,
            sha256: postHogSha256,
          },
          {
            identity: "google-drive",
            category: "formComponents",
            hostInterfaceVersion: 1,
            path: `browser-plugins/${googleDriveSha256}.js`,
            sha256: googleDriveSha256,
            preparation: {
              kind: "stylesheet",
              path: `browser-plugins/${googleDriveStylesheetSha256}.css`,
              sha256: googleDriveStylesheetSha256,
            },
          },
        ],
      })}\n`,
    )
  }
  const outputModulePath = join(tempDir, "generated/loaders.tsx")
  const outputPreparationPath = join(tempDir, "generated/preparation.ts")
  generateOrganisationFrontendPluginComposition({
    manifestPath,
    outputModulePath,
    outputPreparationModulePath: outputPreparationPath,
    outputReportPath: join(tempDir, "generated/report.json"),
  })
  return {
    loaders: readFileSync(outputModulePath, "utf8"),
    preparation: readFileSync(outputPreparationPath, "utf8"),
  }
}

afterEach(() => {
  if (tempDir) rmSync(tempDir, { recursive: true, force: true })
  tempDir = undefined
})

describe("generic Dashboard distribution", () => {
  test("no-plugin organisation emits no loaders", () => {
    const { loaders, preparation } = generate({
      analytics: [],
      formComponents: [],
    })

    expect(loaders).toContain("return {\n\n  }")
    expect(loaders).not.toContain("import(")
    expect(preparation.trim()).toBe(
      "// Generated by prepare-build-inputs. Do not edit.",
    )
  })

  test("composes PostHog and Google Drive from the organisation artifact", () => {
    const { loaders, preparation } = generate(
      {
        analytics: [
          {
            module: "@processfocus/plugin-posthog/register-client",
            type: "analytics.posthog",
          },
        ],
        formComponents: [
          {
            module: "@processfocus/plugin-google-drive/register-client",
            type: "google-drive",
          },
        ],
      },
      true,
    )

    expect(loaders).toContain('"analytics.posthog": artifactLoader')
    expect(loaders).toContain('"google-drive": artifactLoader')
    expect(loaders).toContain("artifact.shouldActivate")
    expect(loaders).not.toContain("shouldActivatePostHogFrontendClientPlugin")
    expect(preparation).toMatch(
      /import "\.\/browser-plugins\/[a-f0-9]{64}\.css"/,
    )
    expect(preparation).not.toContain("@processfocus/plugin-google-drive")
  })
})
